projectFolder/youtubeTimer/finalapp/urls.py
from django.urls import path
from django.http import HttpResponse
from .views import home_view
from .views import person_view
from .views import stopwatch_view
from .views import newDay_view
from .views import success_page_view
from .views import calendar_view
from .views import login_view



urlpatterns = [
    path('', login_view, name='login'),
    path('home.html', home_view, name='home'),
    path('person.html', person_view, name='person'),
    path('stopwatch.html', stopwatch_view, name='stopwatch'),
    path('newDay.html', newDay_view, name='new_day'),
    path('success_page/', success_page_view, name='success_page'),
    path('calendar.html', calendar_view, name='calendar_view'),
    path('login.html', login_view, name='login_view'),
]

projectFolder/youtubeTimer/youtubeTimer/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    
    path('CNIT581-048-Milestone4/', include('finalapp.urls')),
    path('admin/', admin.site.urls),
    path('person/', include('finalapp.urls')),
    path('home/', include('finalapp.urls')),
    path('stopwatch/', include('finalapp.urls')),
    path('newDay/', include('finalapp.urls')),
    path('success_page/', include('finalapp.urls')),
    path('calendar/', include('finalapp.urls')),
    path('CNIT581-048-Milestone4/', include('finalapp.urls')),
]

projectFolder/youtubeTimer/finalapp/models.py
from django.db import models

# Create your models here.
class NewDay(models.Model):
    date = models.DateField()
    hours = models.IntegerField()
    minutes = models.IntegerField()


class StopwatchEntry(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    hours = models.IntegerField(default=0)
    minutes = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.date} - {self.hours} hours {self.minutes} minutes"
    
class UserAccount(models.Model):
    username = models.CharField(max_length=50, default='Matheny')
    email = models.EmailField(default='luke@gmail.com')
    password = models.CharField(max_length=50, default='password')  # Simplified example, use Django's authentication system in a real-world scenario

    def __str__(self):
        return self.username
    

class UserCredentials(models.Model):
    correct_username = models.CharField(max_length=50, default='demo')
    correct_password = models.CharField(max_length=50, default='demo')

    def __str__(self):
        return self.correct_username
    
class Person(models.Model):
    nickname = models.CharField(max_length=255, default='Bon')
    bio = models.TextField(default='Lives in Tampa')
    age = models.IntegerField(default=22)

projectFolder/youtubeTimer/finalapp/forms.py
from django import forms
from .models import NewDay
from .models import UserAccount
from .models import Person

class NewDayForm(forms.ModelForm):
    class Meta:
        model = NewDay
        fields = ['date', 'hours', 'minutes']


class EditNewDayForm(forms.ModelForm):
    class Meta:
        model = NewDay
        fields = ['date', 'hours', 'minutes']

class UserAccountForm(forms.ModelForm):
    class Meta:
        model = UserAccount
        fields = ['username', 'email', 'password']


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ['nickname', 'bio', 'age']

projectFolder/youtubeTimer/finalapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import NewDay
from .forms import NewDayForm  # Import the form you created for NewDay
from .forms import EditNewDayForm
from .models import StopwatchEntry
from .forms import UserAccountForm
from .models import UserAccount
from django.http import JsonResponse
from .forms import PersonForm
from .models import Person
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.


# def home_view(request):
#     if request.method == 'POST':
#         username = request.POST.get('username')
#         password = request.POST.get('password')
#         if username == 'test' and password == 'pass':
#             return render(request, 'home.html')  # Change 'base.html' to 'logo.html'
#         else:
#             return HttpResponse('Invalid credentials. Please try again.')
#     else:
#         return render(request, 'login.html')

def home_view(request):
    if request.headers.get('x-requested-with') == 'XMLHttpRequest' and request.method == 'GET':
        # Assuming you have a dynamic way to generate the links
        new_video_links = [

            "https://www.youtube.com/embed/jfKfPfyJRdk",
            "https://www.youtube.com/embed/6H-PLF2CR18",
            "https://www.youtube.com/embed/CfPxlb8-ZQ0",
            "https://www.youtube.com/embed/Na-YCNomwVw",
         
            "https://www.youtube.com/embed/X28GzyyN6G4",
            "https://www.youtube.com/embed/EilXptlNHPc",
            "https://www.youtube.com/embed/dKvJPrGN2zo",
            "https://www.youtube.com/embed/ySmjheVxYc4",


            "https://www.youtube.com/embed/n61ULEU7CO0",
            "https://www.youtube.com/embed/sca4VG9b0NY",
            "https://www.youtube.com/embed/GcUF2z_Yt5Y",
            "https://www.youtube.com/embed/5zTANw0sevA",


            "https://www.youtube.com/embed/0mtcvqslhIA",
            "https://www.youtube.com/embed/EHnStnU90Ww",
            "https://www.youtube.com/embed/VSlEbE4SvLk",
            "https://www.youtube.com/embed/4xCRgK79DJ4",


        ]
        return JsonResponse({'new_video_links': new_video_links})

    # Render the home page template for non-AJAX requests
    return render(request, 'home.html')



def stopwatch_view(request):
    # Retrieve existing entries from the database
    entries = StopwatchEntry.objects.all()

    # Pass the entries to the template
    return render(request, 'stopwatch.html', {'entries': entries})

def newDay_view(request):
    if request.method == 'POST':
        form = NewDayForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home.html')  # Update to the correct name
    else:
        form = NewDayForm()

    return render(request, 'newDay.html', {'form': form})

def success_page_view(request):
    return render(request, 'success_page.html')


def calendar_view(request):
    calendar_data = NewDay.objects.all()

    # Set the number of entries per page
    entries_per_page = 10

    # Use Django's Paginator to paginate the queryset
    paginator = Paginator(calendar_data, entries_per_page)

    # Get the current page number from the request's GET parameters
    page = request.GET.get('page')

    try:
        # Get the Page object for the current page
        calendar_data = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        calendar_data = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g., 9999), deliver last page.
        calendar_data = paginator.page(paginator.num_pages)

    if request.method == 'POST':
        form = EditNewDayForm(request.POST)
        if 'delete_entry' in request.POST:
            # Handle deletion
            entry_id = request.POST.get('delete_entry')
            entry = get_object_or_404(NewDay, id=entry_id)
            entry.delete()
            return redirect('calendar_view')
        elif form.is_valid():
            # Handle editing
            entry_id = form.cleaned_data['id']
            new_day_entry = get_object_or_404(NewDay, id=entry_id)
            form = EditNewDayForm(request.POST, instance=new_day_entry)
            if form.is_valid():
                form.save()
                return redirect('calendar_view')
    else:
        form = EditNewDayForm()

    return render(request, 'calendar.html', {'calendar_data': calendar_data, 'form': form})


def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Hardcoded values for testing
        hardcoded_username = 'Matheny'
        hardcoded_password = 'password'

        if username == hardcoded_username and password == hardcoded_password:
            # Login successful
            response_data = {'success': True, 'redirect_url': '/CNIT581-048-Milestone4/home.html'}
        else:
            # Login failed
            response_data = {'success': False, 'login_failed': True}

        return JsonResponse(response_data)

    return render(request, 'login.html', {'login_failed': False})

def person_view(request):
    # Try to get the existing person object with ID=1 or create it if it doesn't exist
    person, created = Person.objects.get_or_create(id=1, defaults={'nickname': 'Bon', 'bio': 'Lives in Tampa', 'age': 22})

    if request.method == 'POST':
        form = PersonForm(request.POST, instance=person)
        if form.is_valid():
            form.save()
            return redirect('person.html')  # Redirect to the same page after form submission
    else:
        form = PersonForm(instance=person)

    return render(request, 'person.html', {'person': person, 'form': form})

projectFolder/youtubeTimer/finalapp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'navbar.css' %}"> <!-- Link to your external CSS file for navigation bar styling -->
    <link rel="stylesheet" href="{% static 'index.css' %}"> <!-- Link to your external CSS file for page styling -->
</head>

<body>

    <div class="topnav">
        <a href="home.html"><img src="{% static 'ytog.png' %}" alt="Home"></a> <!-- Image button for Home -->
        <div class="nav-right">
            <a href="stopwatch.html"><img src="{% static 'stopwatch.png' %}" alt="Stopwatch"></a> <!-- Image button for Stopwatch, linking to stopwatch.html -->
            <a href="person.html"><img src="{% static 'person.png' %}" alt="Person"></a> <!-- Image button for Person, linking to person.html -->
        </div>
    </div>

<div class="timer-container">
    <span id="timer">Focused Work Goal: <span id="timerHours">08</span>:<span id="timerMinutes">00</span>:00</span>
</div>

<!-- Add this section below your timer-container -->

<div class="video-thumbnail">
    <img src="{% static 'play.png' %}" alt="Play Button" class="play-button">
</div>

<script>
    // Retrieve the values of hours and minutes from the query parameters (URL parameters)
    const urlParams = new URLSearchParams(window.location.search);
    const hours = urlParams.get("hiddenHours");
    const minutes = urlParams.get("hiddenMinutes");

    // If no values are passed, set default values (8 hours)
    const defaultHours = "08";
    const defaultMinutes = "00";

    // Update the timer elements with the values (either passed or default)
    const timerHours = document.getElementById("timerHours");
    const timerMinutes = document.getElementById("timerMinutes");
    timerHours.textContent = (hours || defaultHours).padStart(2, "0");
    timerMinutes.textContent = (minutes || defaultMinutes).padStart(2, "0");
</script>

</body>
</html>

projectFolder/youtubeTimer/finalapp/templates/calendar.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <title>Calendar</title>
    <link rel="stylesheet" href="{% static 'navbar.css' %}">
    <link rel="stylesheet" href="{% static 'calendar.css' %}">
</head>

<body>
    <div class="topnav">
        <a href="home.html"><img src="{% static 'ytog.png' %}" alt="Home"></a>
        <div class="nav-right">
            <a href="stopwatch.html"><img src="{% static 'stopwatch.png' %}" alt="Stopwatch"></a>
            <a href="person.html"><img src="{% static 'person.png' %}" alt="Person"></a>
        </div>
    </div>

    <div>
        <h1>TIMER HISTORY</h1>
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Hours</th>
                    <th>Minutes</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for entry in calendar_data %}
                    <tr>
                        <td>{{ entry.date }}</td>
                        <td>{{ entry.hours }}</td>
                        <td>{{ entry.minutes }}</td>
                        <td>
                            <form method="post" action="{% url 'calendar_view' %}">
                                {% csrf_token %}
                                <input type="hidden" name="delete_entry" value="{{ entry.id }}">
                                <button type="submit">Delete</button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        
        <div class="pagination">
            {% if calendar_data.has_previous %}
                <button class="button">
                    <a href="?page={{ calendar_data.previous_page_number }}">Previous</a>
                </button>
            {% else %}
                <button class="button" disabled>Previous</button>
            {% endif %}
        
            <button class="current">
                Page {{ calendar_data.number }} of {{ calendar_data.paginator.num_pages }}.
            </button>
        
            {% if calendar_data.has_next %}
                <button class="button">
                    <a href="?page={{ calendar_data.next_page_number }}">Next</a>
                </button>
            {% else %}
                <button class="button" disabled>Next</button>
            {% endif %}
        </div>
        
    </div>
</body>

</html>

projectFolder/youtubeTimer/finalapp/templates/calendar_entry_detail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Calendar Entry Details</title>
    <link rel="stylesheet" href="{% static 'details.css' %}">
</head>
<body>
    <div class="details-container">
        <h1>Calendar Entry Details</h1>
        <div class="entry-details">
            <h2>Date: {{ entry.date }}</h2>
            <p>Total Time: {{ entry.total_time }}</p>
            <!-- Display other entry details as needed -->
        </div>
        <a href="javascript:void(0);" onclick="goBack()" class="return-button">Return to Calendar</a>
    </div>

    <script>
    function goBack() {
        window.history.back();
    }
    </script>
</body>
</html>

projectFolder/youtubeTimer/finalapp/templates/edit_entry.html
{% extends "base.html" %}

{% block content %}
  <h1>Edit Calendar Entry</h1>
  <form method="post">
    {% csrf_token %}
    <label for="date">Date:</label>
    <input type="date" name="date" id="date" value="{{ entry.date }}">
    <br>
    <label for="total_time">Total Time:</label>
    <input type="text" name="total_time" id="total_time" value="{{ entry.total_time }}">
    <br>
    <input type="submit" value="Save">
  </form>
{% endblock %}

projectFolder/youtubeTimer/finalapp/templates/home.html
<!DOCTYPE html>
<html lang="en">


<head>
   {% load static %}
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link rel="stylesheet" href="{% static 'navbar.css' %}">
   <link rel="stylesheet" href="{% static 'index.css' %}">
   <title>Home</title>
  
   
   <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
</head>


<body>


   <div class="topnav">
       <a href="home.html"><img src="{% static 'ytog.png' %}" alt="Home"></a>
       <div class="nav-right">
           <a href="stopwatch.html"><img src="{% static 'stopwatch.png' %}" alt="Stopwatch"></a>
           <a href="person.html"><img src="{% static 'person.png' %}" alt="Person"></a>
       </div>
   </div>

   <button type="button" style="display: block; margin: 10px auto; padding: 10px 20px; background-color: #FF0000; color: white; border: none; border-radius: 5px; cursor: pointer;" onclick="refreshVideos()" id="focusModeButton">ENFORCE FOCUS MODE</button>




   <div class="video-grid">
    <!-- Repeat the following block for each video -->
    <div class="video-container">
        <iframe src="https://www.youtube.com/embed/nur4RYo2OQk" frameborder="0" allowfullscreen></iframe>
    </div>


    <!-- Repeat the block above to create a 4x4 grid -->
    <!-- Example: -->
    <div class="video-container">
        <iframe src="https://www.youtube.com/embed/mwKJfNYwvm8" frameborder="0" allowfullscreen></iframe>
    </div>


    <div class="video-container">
        <iframe src="https://www.youtube.com/embed/2ko5FQyDiS0" frameborder="0" allowfullscreen></iframe>
    </div>


    <!-- Repeat the block above to create a 4x4 grid -->
    <!-- Example: -->
    <div class="video-container">
        <iframe src="https://www.youtube.com/embed/rz5TGN7eUcM" frameborder="0" allowfullscreen></iframe>
    </div>   <div class="video-container">
        <iframe src="https://www.youtube.com/embed/NKdJ-xV-p_g" frameborder="0" allowfullscreen></iframe>
    </div>


    <!-- Repeat the block above to create a 4x4 grid -->
    <!-- Example: -->
    <div class="video-container">
        <iframe src="https://www.youtube.com/embed/9fFWawcJXUw" frameborder="0" allowfullscreen></iframe>
    </div>
    <!-- Repeat this block 14 more times to fill the 4x4 grid -->
    <div class="video-container">
        <iframe src="https://www.youtube.com/embed/rLYwIQmxF_Q" frameborder="0" allowfullscreen></iframe>
    </div>


    <!-- Repeat the block above to create a 4x4 grid -->
    <!-- Example: -->
    <div class="video-container">
        <iframe src="https://www.youtube.com/embed/muUL8kOqeyE" frameborder="0" allowfullscreen></iframe>
    </div>


       <div class="video-container">
        <iframe src="https://www.youtube.com/embed/O2AbcCbyJ2U" frameborder="0" allowfullscreen></iframe>
    </div>


    <!-- Repeat the block above to create a 4x4 grid -->
    <!-- Example: -->
    <div class="video-container">
        <iframe src="https://www.youtube.com/embed/nzciqaNN4I0" frameborder="0" allowfullscreen></iframe>
    </div>




    <!-- Example: -->
    <div class="video-container">
        <iframe src="https://www.youtube.com/embed/aPO5JaShu2U" frameborder="0" allowfullscreen></iframe>
    </div>


       <div class="video-container">
        <iframe src="https://www.youtube.com/embed/8IQbF0IK-f4" frameborder="0" allowfullscreen></iframe>
    </div>


       <!-- Example: -->
       <div class="video-container">
        <iframe src="https://www.youtube.com/embed/Hz2F_S3Tl0Y" frameborder="0" allowfullscreen></iframe>
    </div>


       <div class="video-container">
        <iframe src="https://www.youtube.com/embed/2Gw4K7oqK08" frameborder="0" allowfullscreen></iframe>
    </div>


       <!-- Example: -->
       <div class="video-container">
        <iframe src="https://www.youtube.com/embed/CdOQEQ3GF6c" frameborder="0" allowfullscreen></iframe>
    </div>


       <div class="video-container">
        <iframe src="https://www.youtube.com/embed/REM3sD7FatY" frameborder="0" allowfullscreen></iframe>
    </div>



</div>


   <script>
       const apiUrl = 'https://api.quotable.io/random?tags=success';
       let buttonClicked = false;  // Variable to track button state


       function fetchAndDisplayQuote() {
           const quoteContainer = document.querySelector('.quote-container');
           const quote = document.querySelector('.quote');
           const authorText = document.querySelector('.author');
           const authorName = document.querySelector('.author-name');


           quote.textContent = 'loading...';
           authorText.textContent = '';
           authorName.textContent = '';


           fetch(apiUrl)
               .then(response => response.json())
               .then(data => {
                   if (data.content && data.content.trim() !== "") {
                       quote.textContent = data.content;
                       authorText.textContent = 'by:';
                       authorName.textContent = data.author;
                   } else {
                       fetchAndDisplayQuote();
                   }
               })
               .catch(error => {
                   console.error('Error getting quote:', error);
               });
       }

       function refreshVideos() {
        $.ajax({
            type: 'GET',
            url: '',
            success: function (response) {
                updateVideoLinks(response.new_video_links);
            },
            error: function (error) {
                console.error('Error refreshing videos:', error);
            }
        });

        document.getElementById('focusModeButton').style.display = 'none';
        setTimeout(function () {
            document.getElementById('focusModeButton').innerText = 'REFRESH PAGE TO EXIT FOCUS MODE';
        }, 100);
    }

    function updateVideoLinks(newVideoLinks) {
        const videoGrid = document.querySelector('.video-grid');
        videoGrid.innerHTML = '';

        newVideoLinks.forEach(link => {
            const videoContainer = document.createElement('div');
            videoContainer.className = 'video-container';

            const iframe = document.createElement('iframe');
            iframe.src = link;
            iframe.frameborder = 0;
            iframe.allowfullscreen = true;

            videoContainer.appendChild(iframe);
            videoGrid.appendChild(videoContainer);
        });
    }

    fetchAndDisplayQuote();
   </script>
</body>


</html>

projectFolder/youtubeTimer/finalapp/templates/index.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'navbar.css' %}"> <!-- Link to your external CSS file for navigation bar styling -->
    <link rel="stylesheet" href="{% static 'index.css' %}"> <!-- Link to your external CSS file for page styling -->
</head>

<body>

    <div class="topnav">
        <a href="home.html"><img src="{% static 'ytog.png' %}" alt="Home"></a> <!-- Image button for Home -->
        <div class="nav-right">
            <a href="stopwatch.html"><img src="{% static 'stopwatch.png' %}" alt="Stopwatch"></a> <!-- Image button for Stopwatch, linking to stopwatch.html -->
            <a href="person.html"><img src="{% static 'person.png' %}" alt="Person"></a> <!-- Image button for Person, linking to person.html -->
        </div>
    </div>

<div class="timer-container">
    <span id="timer">Focused Work Goal: <span id="timerHours">008</span>:<span id="timerMinutes">00</span>:00</span>
</div>

<!-- Add this section below your timer-container -->

<div class="video-thumbnail">
    <img src="{% static 'play.png' %}" alt="Play Button" class="play-button">
</div>

<script>
    // Retrieve the values of hours and minutes from the query parameters (URL parameters)
    const urlParams = new URLSearchParams(window.location.search);
    const hours = urlParams.get("hiddenHours");
    const minutes = urlParams.get("hiddenMinutes");

    // If no values are passed, set default values (8 hours)
    const defaultHours = "08";
    const defaultMinutes = "00";

    // Update the timer elements with the values (either passed or default)
    const timerHours = document.getElementById("timerHours");
    const timerMinutes = document.getElementById("timerMinutes");
    timerHours.textContent = (hours || defaultHours).padStart(2, "0");
    timerMinutes.textContent = (minutes || defaultMinutes).padStart(2, "0");
</script>

</body>
</html>

projectFolder/youtubeTimer/finalapp/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'login.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <title>Login</title>
</head>

<body>

    <div class="login-container">
        <h2>Youtube Work Tracker</h2>

        {% if login_failed %}
        <p class="error-message">Invalid username or password. Please try again.</p>
        {% endif %}

        <form id="loginForm" method="post" action=''>
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" required>

            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>

            <button type="button" onclick="submitForm()">Login</button>
        </form>
    </div>

    <script>
        function submitForm() {
            var username = $('#username').val();
            var password = $('#password').val();

            $.ajax({
                type: 'POST',
                url: '',
                data: {
                    'username': username,
                    'password': password,
                    'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                },
                dataType: 'json',
                success: function (data) {
                    if (data.success) {
                        window.location.href = data.redirect_url;
                    } else {
                        $('.error-message').text('Invalid username or password. Please try again.');
                    }
                },
                error: function () {
                    console.log('Error in AJAX request');
                }
            });
        }
    </script>

</body>

</html>

projectFolder/youtubeTimer/finalapp/templates/newDay.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>New Day</title>
    <link rel="stylesheet" href="{% static 'navbar.css' %}">
    <link rel="stylesheet" href="{% static 'newDay.css' %}">
</head>

<body>
    <div class="topnav">
        <a href="home.html"><img src="{% static 'ytog.png' %}" alt="Home"></a>
        <div class="nav-right">
            <a href="stopwatch.html"><img src="{% static 'stopwatch.png' %}" alt="Stopwatch"></a>
            <a href="person.html"><img src="{% static 'person.png' %}" alt="Person"></a>
        </div>
    </div>

    <div class="form-container">
        <h2 class="new-day-text">Start a New Day</h2>
        <form method="post" id="newDayForm" action="{% url 'new_day' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="date">Date:</label>
                <input type="date" id="date" name="date" required>
            </div>

            <div class="form-group">
                <label for="hours">Time Goal for the Day (Hours):</label>
                <input type="number" id="hours" name="hours" min="0" max="23" value="0" class="slider">
            </div>

            <div class="form-group">
                <label for="minutes">Time Goal for the Day (Minutes):</label>
                <input type="number" id="minutes" name="minutes" min="0" max="59" value="0" class="slider">
            </div>

            <input type="submit" value="Create">
        </form>
    </div>

    <!-- JavaScript to update slider values -->
    <script>
        const hoursInput = document.getElementById("hours");
        const minutesInput = document.getElementById("minutes");

        const newDayForm = document.getElementById("newDayForm");

        // Add an event listener to the form's submit button
        newDayForm.addEventListener("submit", (event) => {
            // Update the hidden fields with the values
            document.getElementById("hiddenHours").value = hoursInput.value;
            document.getElementById("hiddenMinutes").value = minutesInput.value;

            // Prevent the default form submission behavior
            event.preventDefault();

            // Submit the form manually
            newDayForm.submit();
        });
    </script>

</body>

</html>

projectFolder/youtubeTimer/finalapp/templates/person.html
<!-- person.html -->

{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Person</title>
    <link rel="stylesheet" href="{% static 'person.css' %}">
    <link rel="stylesheet" href="{% static 'navbar.css' %}">
</head>

<body>

    <div class="topnav">
        <a href="home.html"><img src="{% static 'ytog.png' %}" alt="Home"></a>
        <div class="nav-right">
            <a href="stopwatch.html"><img src="{% static 'stopwatch.png' %}" alt="Stopwatch"></a>
            <a href="person.html"><img src="{% static 'person.png' %}" alt="Person"></a>
        </div>
    </div>

    <div class="account-info">
        <p>Additional Account Info</p>
        <!-- Add your additional account information here -->
    </div>
    <form method="post">
        {% csrf_token %}
        <div>
            <label for="id_nickname">Nickname:</label>
            <input type="text" name="nickname" id="id_nickname" value="{{ person.nickname }}">
        </div>
        <div>
            <label for="id_bio">Bio:</label>
            <textarea name="bio" id="id_bio">{{ person.bio }}</textarea>
        </div>
        <div>
            <label for="id_age">Age:</label>
            <input type="number" name="age" id="id_age" value="{{ person.age }}">
        </div>

        <button type="submit">Save Changes</button>
    </form>
</body>

</html>

projectFolder/youtubeTimer/finalapp/templates/success_page.html
<!-- success_page.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Success Page</title>
</head>
<body>
    <h1>Success!</h1>
    <!-- Add content for the success page as needed -->
</body>
</html>